--
-- Relational Schema for test Information Model
-- Generated by ActiveFacts Schema Generator at 2016-10-16T11:10:54+11:00.
--

CREATE TABLE Country (
	-- Country has Country Code
	CountryCodeID                           BIGINT NOT NULL,
	-- Primary index to Country over PresenceConstraint over (Country Code in "Country has Country Code") occurs at most one time
	PRIMARY KEY CLUSTERED(CountryCode, CountryCodeID)
);


CREATE TABLE CountryCode (
	-- Country Code surrogate key
	CountryCodeID                           BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
	-- Country Code Value
	CountryCodeValue                        CHARACTER(3) NOT NULL,
	-- Primary index to Country Code
	PRIMARY KEY CLUSTERED(CountryCodeID),
	-- Unique index to Country Code
	UNIQUE NONCLUSTERED(CountryCodeValue)
);


ALTER TABLE Country
	ADD FOREIGN KEY (CountryCodeID) REFERENCES CountryCode (CountryCodeID);

