--
-- Relational Schema for test Information Model
-- Generated by ActiveFacts Schema Generator at 2016-10-16T11:11:02+11:00.
--

CREATE TABLE Magnet (
	-- Magnet has Magnet AutoCounter
	MagnetAutoCounter                       BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
	-- Primary index to Magnet over PresenceConstraint over (Magnet AutoCounter in "Magnet has Magnet AutoCounter") occurs at most one time
	PRIMARY KEY CLUSTERED(MagnetAutoCounter)
);


CREATE TABLE MagnetPole (
	-- MagnetPole surrogate key
	MagnetPoleID                            BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
	-- MagnetPole belongs to Magnet that has Magnet AutoCounter
	MagnetAutoCounter                       BIGINT NOT NULL,
	-- MagnetPole Is North
	IsNorth                                 BOOLEAN,
	-- Primary index to MagnetPole
	PRIMARY KEY CLUSTERED(MagnetPoleID),
	-- Unique index to MagnetPole over PresenceConstraint over (Magnet, Is North in "MagnetPole belongs to Magnet", "MagnetPole is north") occurs at most one time
	UNIQUE NONCLUSTERED(MagnetAutoCounter, IsNorth),
	FOREIGN KEY (MagnetAutoCounter) REFERENCES Magnet (MagnetAutoCounter)
);


