CREATE TABLE MAGNET (
	-- Magnet has Magnet AutoCounter
	MAGNET_AUTO_COUNTER                     LONGINTEGER NOT NULL GENERATED BY DEFAULT ON NULL AS IDENTITY,
	-- Primary index to Magnet(Magnet AutoCounter in "Magnet has Magnet AutoCounter")
	PRIMARY KEY(MAGNET_AUTO_COUNTER)
);


CREATE TABLE MAGNET_POLE (
	-- MagnetPole belongs to Magnet that has Magnet AutoCounter
	MAGNET_AUTO_COUNTER                     LONGINTEGER NOT NULL,
	-- MagnetPole Is North
	IS_NORTH                                CHAR(1),
	-- Primary index to MagnetPole(Magnet, Is North in "MagnetPole belongs to Magnet", "MagnetPole is north")
	PRIMARY KEY(MAGNET_AUTO_COUNTER, IS_NORTH),
	FOREIGN KEY (MAGNET_AUTO_COUNTER) REFERENCES MAGNET (MAGNET_AUTO_COUNTER)
);


